export const SUBMIT_BUTTON_CLICKED_LOGIN = 'SUBMIT_BUTTON_CLICKED_LOGIN'
export const SET_FORM_CONFIRMED_LOGIN = 'SET_FORM_CONFIRMED_LOGIN'
export const CLEAR_LOGIN_VALIDATOR = 'CLEAR_LOGIN_VALIDATOR'


//inputs
export const SET_LOGIN_INPUT_EMAIL = 'SET_LOGIN_INPUT_EMAIL'
export const SET_LOGIN_INPUT_INPUT_PASSWORD = 'SET_LOGIN_INPUT_INPUT_PASSWORD'
//errors
export const SET_LOGIN_INPUT_ERROR_EMAIL = 'SET_LOGIN_INPUT_ERROR_EMAIL'
export const SET_LOGIN_INPUT_ERROR_PASSWORM = 'SET_LOGIN_INPUT_ERROR_PASSWORM'

export const CLEAR_LOGIN_INPUT_ERROR_EMAIL = 'CLEAR_LOGIN_INPUT_ERROR_EMAIL'
export const CLEAR_LOGIN_INPUT_ERROR_PASSWORM = 'CLEAR_LOGIN_INPUT_ERROR_PASSWORM'




