export const SUBMIT_BUTTON_CLICKED_REGISTRATION = 'SUBMIT_BUTTON_CLICKED_REGISTRATION'
export const SET_FORM_CONFIRMED_REGISTRATION = 'SET_FORM_CONFIRMED_REGISTRATION'
export const CLEAR_REGISTRATION_VALIDATOR = 'CLEAR_REGISTRATION_VALIDATOR'


//inputs
export const SET_REG_INPUT_EMAIL = 'SET_REG_INPUTS_EMAIL'
export const SET_REG_INPUT_PASSWORD = 'SET_REG_INPUTS_PASSWORM'
export const SET_REG_INPUT_PASS_CONFIRM = 'SET_REG_INPUTS_PASS_CONFIRM'
export const SET_REG_INPUT_NAME = 'SET_REG_INPUTS_NAME'
//errors
export const SET_REG_ERROR_EMAIL = 'SET_REG_ERROR_EMAIL'
export const SET_REG_ERROR_PASSWORM = 'SET_REG_ERROR_PASSWORM'
export const SET_REG_ERROR_PASS_CONFIRM = 'SET_REG_ERROR_PASS_CONFIRM'
export const SET_REG_ERROR_NAME = 'SET_REG_ERROR_NAME'

export const CLEAR_REG_ERROR_EMAIL = 'CLEAR_REG_ERROR_EMAIL'
export const CLEAR_REG_ERROR_PASSWORM = 'CLEAR_REG_ERROR_PASSWORM'
export const CLEAR_REG_ERROR_PASS_CONFIRM = 'CLEAR_REG_ERROR_PASS_CONFIRM'
export const CLEAR_REG_ERROR_NAME = 'CLEAR_REG_ERROR_NAME'
